apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "renovate.fullname" . }}
  labels:
    {{- include "renovate.labels" . | nindent 4 }}
data:
  config.json: |
    {{ .Values.config.renovate | toJson }}
