apiVersion: v1
kind: Secret
metadata:
  name: {{ include "renovate.fullname" . }}
  labels:
    {{- include "renovate.labels" . | nindent 4 }}
data:
  RENOVATE_TOKEN: {{ .Values.config.renovate.token | b64enc }}
  RENOVATE_API_TOKEN: {{ .Values.config.plural.token | b64enc }}
